feat: drop support for php 8.0
KnpLabs/KnpMenuBundle pull request #471
Opened 2024-02-16 19:59 UTC by Chris53897

migrate phpunit.xml.dist to version 10
allow PHPUnit 11

The change to Attributes, is to fix the deprecation warnings from PHPUnit 11

Maybe it is already time to drop support for php 8.0
https://github.com/KnpLabs/KnpMenuBundle/pull/460#issuecomment-1761147457

2024-03-01 17:55 UTC, garak requested changes
Please add php 8.3

2024-03-01 18:01 UTC, stof commented
Given that KnpMenu still support PHP 8.0, I find it weird to drop it in the bundle (especially with a changelog entry saying it is done to match)

2024-03-01 20:26 UTC, Chris53897 commented
@garak I just rebased.

@stof Yes of course. I planned to add the corresponding PR for Knp Menu as well. But did not had the time yet.

2024-03-10 09:00 UTC, garak approved these changes

2024-03-10 16:14 UTC, derrabus approved these changes

2024-03-11 17:01 UTC, merged